
# cargo-vet audits file

[[audits.bitflags]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "2.4.1 -> 2.4.2"

[[audits.crc]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "3.0.1 -> 3.2.1"

[[audits.heck]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "0.4.1 -> 0.5.0"

[[audits.io-kit-sys]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
version = "0.4.0"

[[audits.io-kit-sys]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "0.4.0 -> 0.4.1"

[[audits.libc]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "0.2.154 -> 0.2.155"

[[audits.log]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "0.4.20 -> 0.4.21"

[[audits.pkg-config]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "0.3.26 -> 0.3.27"

[[audits.pkg-config]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "0.3.29 -> 0.3.30"

[[audits.serialport]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "4.2.2 -> 4.3.0"

[[audits.strsim]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "0.10.0 -> 0.11.0"

[[audits.strsim]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "0.11.0 -> 0.11.1"

[[audits.unescaper]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
version = "0.1.4"

[[audits.utf8parse]]
who = "Ben V. Brown <Ralim@Ralimtek.com>"
criteria = "safe-to-deploy"
delta = "0.2.1 -> 0.2.2"

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2024-11-26"

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-16"
end = "2024-11-26"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-05-18"
end = "2024-11-26"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2024-11-26"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2024-11-26"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2024-11-26"

[[trusted.clap]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2024-11-26"

[[trusted.clap_builder]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-28"
end = "2024-11-26"

[[trusted.clap_derive]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2024-11-26"

[[trusted.clap_lex]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-04-15"
end = "2024-11-26"

[[trusted.colorchoice]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2024-11-26"

[[trusted.is_terminal_polyfill]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2024-05-02"
end = "2025-05-09"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2021-01-27"
end = "2024-11-26"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2020-03-17"
end = "2025-05-09"

[[trusted.mach2]]
criteria = "safe-to-deploy"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2021-11-15"
end = "2025-02-17"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2024-11-26"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2024-11-26"

[[trusted.quote]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-09"
end = "2024-11-26"

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-27"
end = "2024-11-26"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2024-11-26"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2024-11-26"

[[trusted.scopeguard]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2020-02-16"
end = "2024-11-26"

[[trusted.smallvec]]
criteria = "safe-to-deploy"
user-id = 2017 # Matt Brubeck (mbrubeck)
start = "2019-10-28"
end = "2024-11-26"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-11-26"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2024-11-26"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2024-11-26"

[[trusted.thread_local]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-09-07"
end = "2024-11-26"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2024-11-26"

[[trusted.valuable]]
criteria = "safe-to-deploy"
user-id = 10 # Carl Lerche (carllerche)
start = "2022-01-03"
end = "2024-11-26"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2024-11-26"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2024-11-26"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2024-11-26"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2024-11-26"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2024-11-26"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-04-02"
end = "2025-05-09"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2024-11-26"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2024-11-26"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2024-11-26"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2024-11-26"
